version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "my_postgres_source"
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=root
  db2:
    image: "postgres:11"
    container_name: "my_postgres_target"
    ports:
      - "5433:5432"
    volumes:
      - my_dbdata2:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=root
volumes:
  my_dbdata:
  my_dbdata2:

